server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-svc:8764/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: peliculas-actores-svc
        uri: http://peliculas-actores-svc:8011
        predicates:
        - Path=/api/peliculas/**
        filters:
        - StripPrefix=2
      - id: usuarios-criticas-svc
        uri: http://usuarios-criticas-svc:8012
        predicates:
        - Path=/api/usuarios/**
        filters:
        - StripPrefix=2

springdoc:
  api-docs:
    path: /api/api-docs
