server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: servicio-peliculas-actores
        uri: http://localhost:8011
        predicates:
        - Path=/api/peliculas/**
        filters:
        - StripPrefix=2
      - id: servicio-usuarios-criticas
        uri: http://localhost:8012
        predicates:
        - Path=/api/usuarios/**
        filters:
        - StripPrefix=2

springdoc:
  api-docs:
    path: /api/api-docs
