server:
  port: 8012

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-svc:8764/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/peliculasactoresdb?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
    password: admin
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  api-docs:
    path: /api-docs
